// themes.ts
import * as stylex from "@stylexjs/stylex";
import { colors } from "./globalTokens.stylex";

export const light = stylex.createTheme(colors, {
    foregroundR: "63",
    foregroundG: "63",
    foregroundB: "70",
    bgStartR: "214",
    bgStartG: "219",
    bgStartB: "220",
    bgEndR: "255",
    bgEndG: "255",
    bgEndB: "255",
    bgSecondaryR: "228",
    bgSecondaryG: "228",
    bgSecondaryB: "231",
    primaryR: "0",
    primaryG: "170",
    primaryB: "255",
    blackWhiteR: "9",
    blackWhiteG: "9",
    blackWhiteB: "11",
    textMutedR: "113",
    textMutedG: "113",
    textMutedB: "122",
    dangerR: "239",
    dangerG: "68",
    dangerB: "68",
    borderR: "212",
    borderG: "212",
    borderB: "216",
});

export const dark = stylex.createTheme(colors, {
    foregroundR: "161",
    foregroundG: "161",
    foregroundB: "170",
    bgStartR: "20",
    bgStartG: "22",
    bgStartB: "27",
    bgEndR: "0",
    bgEndG: "0",
    bgEndB: "0",
    bgSecondaryR: "24",
    bgSecondaryG: "24",
    bgSecondaryB: "27",
    primaryR: "0",
    primaryG: "170",
    primaryB: "255",
    blackWhiteR: "250",
    blackWhiteG: "250",
    blackWhiteB: "250",
    textMutedR: "113",
    textMutedG: "113",
    textMutedB: "122",
    dangerR: "239",
    dangerG: "68",
    dangerB: "68",
    borderR: "39",
    borderG: "39",
    borderB: "42",
});
