// themes.ts
import * as stylex from "@stylexjs/stylex";
import { colors } from "./globalTokens.stylex";

export const light = stylex.createTheme(colors, {
    foregroundR: "101",
    foregroundG: "104",
    foregroundB: "108",
    bgStartR: "214",
    bgStartG: "219",
    bgStartB: "220",
    bgEndR: "255",
    bgEndG: "255",
    bgEndB: "255",
    bgSecondaryR: "255",
    bgSecondaryG: "255",
    bgSecondaryB: "255",
    bgAltR: "226",
    bgAltG: "229",
    bgAltB: "233",
    primaryR: "8",
    primaryG: "102",
    primaryB: "255",
    blackWhiteR: "8",
    blackWhiteG: "8",
    blackWhiteB: "9",
    textMutedR: "113",
    textMutedG: "113",
    textMutedB: "122",
    dangerR: "239",
    dangerG: "68",
    dangerB: "68",
    borderR: "208",
    borderG: "211",
    borderB: "215",
    shadowR: "0",
    shadowG: "0",
    shadowB: "0",
});

export const dark = stylex.createTheme(colors, {
    foregroundR: "176",
    foregroundG: "179",
    foregroundB: "184",
    bgStartR: "28",
    bgStartG: "28",
    bgStartB: "29",
    bgEndR: "0",
    bgEndG: "0",
    bgEndB: "0",
    bgSecondaryR: "37",
    bgSecondaryG: "39",
    bgSecondaryB: "40",
    bgAltR: "59",
    bgAltG: "61",
    bgAltB: "62",
    primaryR: "8",
    primaryG: "102",
    primaryB: "255",
    blackWhiteR: "226",
    blackWhiteG: "229",
    blackWhiteB: "233",
    textMutedR: "113",
    textMutedG: "113",
    textMutedB: "122",
    dangerR: "239",
    dangerG: "68",
    dangerB: "68",
    borderR: "59",
    borderG: "61",
    borderB: "62",
    shadowR: "0",
    shadowG: "0",
    shadowB: "0",
});
