import * as stylex from "@stylexjs/stylex";
import { colors, spacing, radius, text } from "../../app/globalTokens.stylex";

export const styles = stylex.create({
    wrapper: {
        display: "inline-block",
        position: "relative",
    },
    button: {
        alignItems: "center",
        backgroundColor: {
            default: `rgba(${colors.bgAltR}, ${colors.bgAltG}, ${colors.bgAltB}, 1)`,
            ":hover": `rgba(${colors.bgAltHoverR}, ${colors.bgAltHoverG}, ${colors.bgAltHoverB}, 1)`,
        },
        borderRadius: "100%",
        borderWidth: 0,
        cursor: "pointer",
        display: "flex",
        justifyContent: "center",
        minHeight: "35px",
        minWidth: "35px",
    },
    dropdown: {
        backgroundColor: `rgba(${colors.bgSecondaryR}, ${colors.bgSecondaryG}, ${colors.bgSecondaryB}, 1)`,
        borderRadius: radius.md,
        boxShadow: `0 1px 2px rgba(${colors.shadowR}, ${colors.shadowG}, ${colors.shadowB}, .2)`,
        marginTop: spacing.md,
        minWidth: "350px",
        padding: `${spacing.xs} ${spacing.xxs}`,
        position: "absolute",
        right: 0,
        zIndex: 9999,
    },
    header: {
        alignItems: "center",
        display: "flex",
        gap: spacing.xs,
        marginBottom: spacing.sm,
    },
    heading: {
        color: `rgba(${colors.blackWhiteR}, ${colors.blackWhiteG}, ${colors.blackWhiteB}, 1)`,
        display: "block",
        fontSize: text.p,
        fontWeight: 700,
        marginBottom: spacing.xxxs,
    },
    icon: {
        alignItems: "center",
        backgroundColor: `rgba(${colors.bgAltR}, ${colors.bgAltG}, ${colors.bgAltB}, 1)`,
        borderRadius: "100%",
        color: `rgba(${colors.blackWhiteR}, ${colors.blackWhiteG}, ${colors.blackWhiteB}, 1)`,
        display: "flex",
        justifyContent: "center",
        minHeight: "35px",
        minWidth: "35px",
    },
    item: {
        backgroundColor: {
            default: "transparent",
            ":hover": `rgba(${colors.bgAltR}, ${colors.bgAltG}, ${colors.bgAltB}, 1)`,
        },
        borderRadius: radius.sm,
        caretColor: "transparent",
        cursor: "pointer",
        marginBottom: spacing.xxxs,
        marginLeft: spacing.lg,
        padding: `${spacing.xxs}`,
    },
    itemContent: {
        alignItems: "center",
        display: "flex",
        justifyContent: "space-between",
    },
    title: {
        color: `rgba(${colors.blackWhiteR}, ${colors.blackWhiteG}, ${colors.blackWhiteB}, 1)`,
        display: "block",
        fontWeight: 600,
    },
    description: {
        display: "block",
        fontSize: text.xs,
        paddingRight: spacing.sm,
    },
    radio: {
        backgroundColor: "transparent",
        borderRadius: "50%",
        flexShrink: 0,
        height: "12px",
        left: "-4px",
        outlineColor: `rgba(${colors.borderR}, ${colors.borderG}, ${colors.borderB}, 1)`,
        outlineOffset: "2px",
        outlineStyle: "solid",
        outlineWidth: "2px",
        position: "relative",
        transition: "background-color 0.2s ease, border-color 0.2s ease",
        width: "12px",
    },
    radioSelected: {
        backgroundColor: `rgba(${colors.primaryR}, ${colors.primaryG}, ${colors.primaryB}, 1)`,
        borderColor: `rgba(${colors.primaryR}, ${colors.primaryG}, ${colors.primaryB}, 1)`,
        outlineColor: `rgba(${colors.primaryR}, ${colors.primaryG}, ${colors.primaryB}, 1)`,
    },
});
